//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Winetech.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente
    {
        private string nomeFantasiaCliente;
        private string nomeCompletoCliente;
        private string cnpj;
        private string email;
        private double limiteCredito;
        private int codigoPedido;

        public cliente(string razaoSocial, string nomeFantasiaCliente, string nomeCompletoCliente, string rG, string cPF, DateTime dataNascimento, string cnpj, string email, bool statusCliente, double limiteCredito, int codigoPedido, int codigoEnderecoCliente, int codigoContatoCliente)
        {
            razaosocial = razaoSocial;
            this.nomeFantasiaCliente = nomeFantasiaCliente;
            this.nomeCompletoCliente = nomeCompletoCliente;
            rg = rG;
            cpf = cPF;
            datanascimento = dataNascimento;
            this.cnpj = cnpj;
            this.email = email;
            statuscliente = statusCliente;
            this.limiteCredito = limiteCredito;
            this.codigoPedido = codigoPedido;
            this.codigoEnderecoCliente = codigoEnderecoCliente;
            this.codigoContatoCliente = codigoContatoCliente;
        }

        public int codigoCliente { get; set; }
        public string razaosocial { get; set; }
        public string nomefantasia { get; set; }
        public string nomecompleto { get; set; }
        public string rg { get; set; }
        public string cpf { get; set; }
        public System.DateTime datanascimento { get; set; }
        public string cnpjcliente { get; set; }
        public string emailcliente { get; set; }
        public Nullable<bool> statuscliente { get; set; }
        public decimal limitecredito { get; set; }
        public Nullable<int> codigoEnderecoCliente { get; set; }
        public Nullable<int> codigoContatoCliente { get; set; }
        public Nullable<int> codigoPedidoCliente { get; set; }
    
        public virtual contatoCliente contatoCliente { get; set; }
        public virtual enderecoCliente enderecoCliente { get; set; }
        public virtual pedidoCliente pedidoCliente { get; set; }
    }
}
