//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Winetech.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class fornecedor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public fornecedor()
        {
            this.pedidoFornecedor = new HashSet<pedidoFornecedor>();
        }
    
        public int codigoFornecedor { get; set; }
        public string cnpjFornecedor { get; set; }
        public string razaoSocialFornecedor { get; set; }
        public string nomeFantasiaFornecedor { get; set; }
        public string emailFornecedor { get; set; }
        public string telefoneFornecedor { get; set; }
        public Nullable<bool> statusFornecedor { get; set; }
        public Nullable<int> codigoEnderecoFornecedor { get; set; }
    
        public virtual enderecoFornecedor enderecoFornecedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pedidoFornecedor> pedidoFornecedor { get; set; }
    }
}
