//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Winetech.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedidoFornecedor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pedidoFornecedor()
        {
            this.fornecedor = new HashSet<fornecedor>();
        }
    
        public int codigoPedidoFornecedor { get; set; }
        public Nullable<decimal> totalPedidoFornecedor { get; set; }
        public Nullable<int> quantidadePedidoFornecedor { get; set; }
        public Nullable<System.DateTime> dataCompraPedido { get; set; }
        public Nullable<decimal> precoUnitario { get; set; }
        public Nullable<bool> statusPedidofornecedor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fornecedor> fornecedor { get; set; }
    }
}
