//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using WinFormswithEFSample;

namespace Winetech.Model
{
    
    public class perfil
    {
        //[ForeignKey ("usuario") ]
        [Key ]
        public int codigoPerfil { get; set; }
        public string descricaoPerfil { get; set; }
        public virtual usuario usuarios { get { return usuarios; } }

        public perfil(int codigoPerfil, string descricaoPerfil)
        {
            this.codigoPerfil = codigoPerfil;
            this.descricaoPerfil = descricaoPerfil;
        }

        public perfil()
        {
        }
    }
}
