//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using WinFormswithEFSample;

namespace Winetech.Model
{
    
    public class perfil
    {
        private readonly ObservableListSource<perfil> umperfil = new ObservableListSource<perfil>();

        public perfil(int codigoPerfil, string descricaoPerfil)
        {
            this.codigoPerfil = codigoPerfil;
            this.descricaoPerfil = descricaoPerfil;
        }

        public int codigoPerfil { get; set; }
        public string descricaoPerfil { get; set; }
        public virtual ObservableListSource<perfil> perfis {get { return perfis; } }
    }
}
