//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Winetech.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class produto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public produto()
        {
            this.pedidoCliente = new HashSet<pedidoCliente>();
        }
    
        public int codigoProduto { get; set; }
        public string nome { get; set; }
        public string descricao { get; set; }
        public string uva { get; set; }
        public string classe { get; set; }
        public string teor_Alcolico { get; set; }
        public string tipo { get; set; }
        public decimal custoUnitário { get; set; }
        public decimal quantidadeEstoque { get; set; }
        public decimal precoVenda { get; set; }
        public string unidade { get; set; }
        public Nullable<System.DateTime> dataValidade { get; set; }
        public Nullable<int> codigoPais { get; set; }
        public Nullable<int> codigoSafra { get; set; }
        public Nullable<bool> statusProduto { get; set; }
    
        public virtual pais pais { get; set; }
        public virtual safra safra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pedidoCliente> pedidoCliente { get; set; }
    }
}
