//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Windows.Forms;
namespace Winetech.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        private string v;

        public int codigoUsuario { get; set; }
        public string llogin { get; set; }
        public string senha { get; set; }
        public string cpfUsuario { get; set; }
        public string nomecompleto { get; set; }
        public Nullable<bool> statusUsuario { get; set; }
        public Nullable<int> codigoPerfil { get; set; }
        public virtual perfil perfil { get; set; }

        public usuario( int codigo,string login,string senha,string cpf,string nome,bool status,int codigoperfil )
        {
            codigoUsuario = 8;
            llogin = login;
            this.senha = senha;
            cpfUsuario = cpf;
            nomecompleto = nome;
            statusUsuario = status;
            codigoPerfil = codigoperfil;
        }

        public usuario(string nome)
        {
            nomecompleto = nome;
        }

        public bool inserir(usuario u) {
            WinetechEntities ctx = new WinetechEntities();
            var usuario = u;
            try
            {
                ctx.usuario.Add(usuario);
                ctx.SaveChanges();
                return true;
            }
            catch (Exception e) {
                MessageBox.Show(e.ToString(),"Erro:",MessageBoxButtons.OK);
                return false;
            }
        }
        
    }

}
