//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Winetech.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public int codigoUsuario { get; set; }
        public string llogin { get; set; }
        public string senha { get; set; }
        public string cpfUsuario { get; set; }
        public string nomecompleto { get; set; }
        public Nullable<bool> statusUsuario { get; set; }
        public Nullable<int> codigoPerfil { get; set; }
        public virtual perfil perfil { get; set; }

        public usuario( string login,string senha,string cpf,string nome,bool status,int codigoperfil )
        {
            llogin = login;
            this.senha = senha;
            cpfUsuario = cpf;
            nomecompleto = nome;
            statusUsuario = status;
            codigoPerfil = codigoperfil;
        }
        WinetechEntities ctx = new WinetechEntities();
        public bool inserir(usuario u) {
            try
            {
                ctx.usuario.Add(u);
                ctx.SaveChanges();
                return true;
            }
            catch (Exception e) {
                using System.Windows.Forms.MessageBox("Erro:", "Erro", e.ToString);
            }
        }
    }

}
