//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Winetech.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WinetechEntities : DbContext
    {
        public WinetechEntities()
            : base("name=WinetechEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<contatoCliente> contatoCliente { get; set; }
        public virtual DbSet<enderecoCliente> enderecoCliente { get; set; }
        public virtual DbSet<enderecoFornecedor> enderecoFornecedor { get; set; }
        public virtual DbSet<fornecedor> fornecedor { get; set; }
        public virtual DbSet<pais> pais { get; set; }
        public virtual DbSet<pedidoCliente> pedidoCliente { get; set; }
        public virtual DbSet<pedidoFornecedor> pedidoFornecedor { get; set; }
        public virtual DbSet<perfil> perfil { get; set; }
        public virtual DbSet<produto> produto { get; set; }
        public virtual DbSet<safra> safra { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
