//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Winetech.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WinetechEntities : DbContext
    {
        public WinetechEntities()
            : base("Data Source=(LocalDB)\\MSSQLLocalDB;Integrated Security=True;Connect Timeout=30;User Instance=False;")
        {

        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Entity<usuario>().ToTable("usuario");
            modelBuilder.Entity<perfil>().ToTable("perfil");
            modelBuilder.Entity<cliente>().ToTable("cliente");
            modelBuilder.Entity<enderecoCliente>().ToTable("enderecoCliente");
            modelBuilder.Entity<contatoCliente>().ToTable("contatoCliente");
            modelBuilder.Entity<pedidoCliente>().ToTable("pedidoCliente");
            modelBuilder.Entity<produto>().ToTable("produto");
            modelBuilder.Entity<pais>().ToTable("pais");
            modelBuilder.Entity<safra>().ToTable("safra");
            modelBuilder.Entity<fornecedor>().ToTable("fornecedor");
            modelBuilder.Entity<pedidoFornecedor>().ToTable("enderecoCliente");

        }
    
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<contatoCliente> contatoCliente { get; set; }
        public virtual DbSet<enderecoCliente> enderecoCliente { get; set; }
        public virtual DbSet<enderecoFornecedor> enderecoFornecedor { get; set; }
        public virtual DbSet<fornecedor> fornecedor { get; set; }
        public virtual DbSet<pais> pais { get; set; }
        public virtual DbSet<pedidoCliente> pedidoCliente { get; set; }
        public virtual DbSet<pedidoFornecedor> pedidoFornecedor { get; set; }
        public virtual DbSet<perfil> perfil { get; set; }
        public virtual DbSet<produto> produto { get; set; }
        public virtual DbSet<safra> safra { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
